### ISSUE TITLE
Allow installing dependencies

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/github-action#3]
For tests and scripts (and occasionally new versions of Vyper that haven't released yet), it would be really handy to install additional requirements besides what the base image of ape specifies, maybe something like

```yaml
  - uses: ApeWorX/ape-action@main
    with:
      install: requirements.txt  # Installs via `pip install -r requirements.txt` prior to run
```
